r"""
Run with  py -3  on this machine: plain `python` is MSYS2's and cannot
open a D:\... script path. No shebang here on purpose - the py launcher
honours them, and "/usr/bin/env python" points back at MSYS.

Convert a .sid file (PSID/RSID, e.g. from the High Voltage SID Collection)
into a binary that runs on the Ben Eater 6502.

REQUIRES THE $D400 DECODE. This tool does not touch the tune's code at all,
so the SID must answer at its native $D400. See MEMORY_MAP.md for the
decode that puts it at both $4800 and $D400.

Why no address patching: a .sid file is a compiled blob. Finding every
SID access in a binary means disassembling it, and you would still miss
any that are computed, self-modified, or indexed off a pointer. Porting
from source works because the addresses are text; here they are not.

The tune is emitted at its own load address, followed by a driver that
polls the VIA T1 flag - no IRQ, no NMI, no WAI. When there is room below
$4000 the driver also shows the tune's title and author on an HD44780 at
$4C00; when there is not, it falls back to the bare 37-byte driver rather
than refusing the tune.

Usage:
  python SidToBE6502.py <file.sid> [song] [rate_hz]

  song     0-based song index. Default is the file's own start song.
  rate_hz  override the call rate. Default comes from the PSID speed
           field: 50 Hz for a vsync song, 60 Hz for a CIA-timed one
           (a guess - CIA tunes set their own period, which the header
           does not record).

Output: BE6502_<name>[_songN].bin, plus the WozMon load and run addresses.
"""
import io, os, re, struct, subprocess, sys

ACME = r"D:/Documents/Arduino/Assembly/acme/acme.exe"
RAM_TOP = 0x4000          # RAM is decoded only for A15=0 and A14=0


def be16(b, o):
    return struct.unpack('>H', b[o:o + 2])[0]


def text(b, o):
    return b[o:o + 32].split(b'\x00')[0].decode('latin-1').strip()


def quotable(s):
    """Trim to something safe to put inside an ACME string literal."""
    out = ''.join(c if 32 <= ord(c) < 127 and c not in '"\\' else ' ' for c in s)
    return out[:16].ljust(16)


# ---------------------------------------------------------------------------
# HD44780 in 4-bit mode through a 74LS574 latch at $4C00.
#   Q0-Q3 -> D4-D7, Q4 -> RS, Q5 -> E, LCD RW grounded.
# Plain 6502 - Y is saved in zero page rather than with PHY, so this
# assembles for any CPU the tune might have been written for.
# ---------------------------------------------------------------------------
LCD_SOURCE = """
LCDNib
        and #$0f
        ora LCDRS
        sta LCDTMP
        sta LCD                 ; data valid, E low
        ora #LCD_E
        sta LCD                 ; E high
        lda LCDTMP
        sta LCD                 ; E low -> latched
        rts

LCDByte
        sty LCDYSAV
        pha
        lsr
        lsr
        lsr
        lsr
        jsr LCDNib              ; high nibble
        pla
        jsr LCDNib              ; low nibble
        jsr LCDDly40
        ldy LCDYSAV
        rts

LCDCmd  pha
        lda #$00
        sta LCDRS
        pla
        jmp LCDByte

LCDChar pha
        lda #LCD_RS
        sta LCDRS
        pla
        jmp LCDByte

LCDLine1
        lda #$80
        jmp LCDCmd
LCDLine2
        lda #$c0
        jmp LCDCmd

LCDPrint
        ldy #$00
lcdpr1  lda (LCDPTR),y
        beq lcdpr2
        jsr LCDChar
        iny
        bne lcdpr1
lcdpr2  rts

LCDInit
        ldx #40                 ; >15ms after power-up
        jsr LCDDlyMS
        lda #$00
        sta LCDRS
        lda #$03                ; sent blind, still in 8-bit mode
        jsr LCDNib
        ldx #4
        jsr LCDDlyMS
        lda #$03
        jsr LCDNib
        jsr LCDDly200
        lda #$03
        jsr LCDNib
        jsr LCDDly200
        lda #$02                ; switch to 4-bit
        jsr LCDNib
        jsr LCDDly200
        lda #$28                ; 4-bit, 2 lines, 5x8
        jsr LCDCmd
        lda #$08                ; display off
        jsr LCDCmd
        lda #$01                ; clear
        jsr LCDCmd
        ldx #4
        jsr LCDDlyMS
        lda #$06                ; entry mode: increment
        jsr LCDCmd
        lda #$0c                ; display on, cursor off
        jmp LCDCmd

LCDDly40
        ldy #7
lcdd40  dey
        bne lcdd40
        rts
LCDDly200
        ldy #38
lcdd200 dey
        bne lcdd200
        rts
LCDDlyMS                        ; X x ~1.28ms
lcddms1 ldy #$00
lcddms2 dey
        bne lcddms2
        dex
        bne lcddms1
        rts
"""


def build_asm(datfile, org, init, play, song, rate, title, author, use_lcd):
    n = int(round(1000000.0 / rate)) - 2       # VIA T1 free-run period is N+2
    if not 0 <= n <= 0xFFFF:
        raise SystemExit('rate %s Hz is out of range for a 16-bit T1 at 1 MHz' % rate)

    o = []
    o.append(';  generated by SidToBE6502.py - do not edit')
    o.append(';  load $%04X  init $%04X  play $%04X  song %d  %g Hz%s'
             % (org, init, play, song, rate, '  + LCD' if use_lcd else ''))
    o.append('!cpu 6502')
    o.append('VIA_ACR  = $600b')
    o.append('VIA_T1CL = $6004')
    o.append('VIA_T1CH = $6005')
    o.append('VIA_IFR  = $600d')
    if use_lcd:
        o.append('LCD      = $4c00')
        o.append('LCD_RS   = $10')
        o.append('LCD_E    = $20')
        o.append('LCDPTR   = $fa')
        o.append('LCDRS    = $fc')
        o.append('LCDTMP   = $fd')
        o.append('LCDYSAV  = $fe')
    o.append('')
    o.append('* = $%04X' % org)
    o.append('!binary "%s"' % os.path.basename(datfile))
    o.append('')
    o.append('BE6502_START')
    o.append('        sei')
    if use_lcd:
        o.append('        jsr LCDInit')
        o.append('        jsr LCDLine1')
        o.append('        lda #<TitleStr')
        o.append('        sta LCDPTR')
        o.append('        lda #>TitleStr')
        o.append('        sta LCDPTR+1')
        o.append('        jsr LCDPrint')
        o.append('        jsr LCDLine2')
        o.append('        lda #<AuthorStr')
        o.append('        sta LCDPTR')
        o.append('        lda #>AuthorStr')
        o.append('        sta LCDPTR+1')
        o.append('        jsr LCDPrint')
    o.append('        lda #$40           ; ACR: T1 free-run, PB7 disabled')
    o.append('        sta VIA_ACR')
    o.append('        lda #$%02X           ; %d -> N+2 = %d cycles = %g Hz'
             % (n & 0xFF, n, n + 2, rate))
    o.append('        sta VIA_T1CL')
    o.append('        lda #$%02X' % (n >> 8))
    o.append('        sta VIA_T1CH       ; loads latches and starts the timer')
    o.append('        lda #$%02X           ; song number' % song)
    o.append('        tax')
    o.append('        tay')
    o.append('        jsr $%04X          ; tune init' % init)
    o.append('BE6502_LOOP')
    o.append('        jsr $%04X          ; tune play' % play)
    o.append('-       bit VIA_IFR        ; V flag <- bit 6 = T1 timed out')
    o.append('        bvc -')
    o.append('        bit VIA_T1CL       ; reading T1C_L clears the flag')
    o.append('        jmp BE6502_LOOP')
    if use_lcd:
        o.append(LCD_SOURCE)
        o.append('TitleStr  !text "%s"' % quotable(title))
        o.append('          !byte 0')
        o.append('AuthorStr !text "%s"' % quotable(author))
        o.append('          !byte 0')
    return '\n'.join(o) + '\n'


def convert(path, song=None, rate=None):
    raw = io.open(path, 'rb').read()
    magic = raw[:4]
    if magic not in (b'PSID', b'RSID'):
        raise SystemExit('not a PSID/RSID file (magic %r)' % magic)

    version = be16(raw, 0x04)
    data_off = be16(raw, 0x06)
    load = be16(raw, 0x08)
    init = be16(raw, 0x0A)
    play = be16(raw, 0x0C)
    nsongs = be16(raw, 0x0E)
    start = be16(raw, 0x10)
    speed = struct.unpack('>I', raw[0x12:0x16])[0]
    title, author = text(raw, 0x16), text(raw, 0x36)

    data = raw[data_off:]
    if load == 0:                       # load address is the first two data bytes
        load = struct.unpack('<H', data[:2])[0]
        data = data[2:]
    if init == 0:
        init = load

    print('  %-12s %s' % ('title', title))
    print('  %-12s %s' % ('author', author))
    print('  %-12s %s' % ('released', text(raw, 0x56)))
    print('  %-12s %s v%d, %d song%s, starts on %d'
          % ('format', magic.decode(), version, nsongs, 's' if nsongs != 1 else '', start))
    print('  %-12s load $%04X-$%04X  init $%04X  play $%04X'
          % ('addresses', load, load + len(data) - 1, init, play))

    song = (start - 1) if song is None else song   # header start song is 1-based
    song = max(0, min(song, nsongs - 1))
    cia = bool(speed >> song & 1) if song < 32 else False
    if rate is None:
        rate = 60.0 if cia else 50.0
    print('  %-12s song %d of %d, %s-timed, calling play at %g Hz'
          % ('playback', song, nsongs, 'CIA' if cia else 'vsync', rate))

    problems = []
    if play == 0:
        problems.append('play address is 0: the tune installs its own IRQ handler '
                        'and drives itself. The polled driver cannot run it.')
    if magic == b'RSID':
        problems.append('RSID files expect a real C64 with the KERNAL present. '
                        'PSID is the format that promises to run standalone.')
    end = load + len(data)
    if end > RAM_TOP:
        problems.append('tune occupies $%04X-$%04X, past the top of RAM ($%04X). '
                        'A binary cannot be relocated.' % (load, end - 1, RAM_TOP))
    if load < 0x0200:
        problems.append('tune loads at $%04X, over zero page and the stack.' % load)
    if problems:
        for p in problems:
            print('  PROBLEM      %s' % p)
        raise SystemExit('cannot convert this one.')

    name = 'BE6502_' + re.sub(r'[^A-Za-z0-9]+', '_',
                              os.path.splitext(os.path.basename(path))[0]).strip('_')
    if song:
        name += '_song%d' % song
    datfile = name + '.dat'
    io.open(datfile, 'wb').write(bytes(data))

    try:
        for use_lcd in (True, False):
            asm = build_asm(datfile, load, init, play, song, rate, title, author, use_lcd)
            io.open(name + '.asm', 'w', newline='\r\n').write(asm)
            r = subprocess.Popen([ACME, '-f', 'plain', '-o', name + '.bin',
                                  '--symbollist', name + '.sym', name + '.asm'],
                                 stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            log = r.communicate()[0].decode('utf-8', 'replace')
            if r.returncode != 0:
                if not use_lcd:
                    raise SystemExit('acme failed:\n' + log.strip()[:600])
                continue
            size = os.path.getsize(name + '.bin')
            if load + size <= RAM_TOP:
                break
            if use_lcd:
                print('  %-12s no room for the LCD code, using the bare driver'
                      % 'note')
            else:
                raise SystemExit('no room for the driver below $%04X' % RAM_TOP)
    finally:
        if os.path.exists(datfile):
            os.remove(datfile)

    entry = None
    for l in io.open(name + '.sym', encoding='utf-8', errors='replace'):
        if l.strip().startswith('BE6502_START'):
            entry = re.search(r'\$([0-9a-fA-F]+)', l).group(1).upper()
    size = os.path.getsize(name + '.bin')
    print('  %-12s %s%s  (%d bytes, ends $%04X)'
          % ('written', name + '.bin', '  + LCD' if use_lcd else '', size, load + size - 1))
    print('  %-12s %04XL   then   %sR' % ('WozMon', load, entry))
    return 0


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    song = int(sys.argv[2]) if len(sys.argv) > 2 else None
    rate = float(sys.argv[3]) if len(sys.argv) > 3 else None
    return convert(sys.argv[1], song, rate)


if __name__ == '__main__':
    sys.exit(main())
